### PR TITLE
Add Kibana Link Endpoint [RHCLOUD-20313]

### PR DESCRIPTION
**Pull request by CodyWMitchell**
## What?
Added an additional endpoint to generate the correct Kibana dashboard url for the front-end. 
(See https://github.com/RedHatInsights/payload-tracker-frontend/pull/106)

## Why?
Allow users to quickly view all logs for a specific request_id in Kibana

## How?
Uses the request_id and the optional service name sent by the user to generate a URL. The search index (grabbed from the Kibana dashboard), Kibana dashboard URL, and service field are all configurable through clowder.

## Testing
Added tests for the new endpoint.

## Anything Else?
Any other notes about the PR that would be useful for the reviewer. 

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by SteveHNH — COMMENTED** [review]
We should probably have an update in clowdapp.yml where we can provide an env variable for the kibana url. Unless I'm missing something, I don't see a place where we can override the url in the config with a different one.

**Review by SteveHNH — APPROVED** [review]

**Review by aleccohan — APPROVED** [review]
Looks great to me!

**Pull request merged**
