### PR TITLE
Adding readiness probe for the payload-tracker api pods [RHCLOUD-19463]

### PR DESCRIPTION
**Pull request by tahmidefaz**
## What?
Adds a readiness probe for the payload tracker API pods.

[Jira](https://issues.redhat.com/browse/RHCLOUD-19463)

## Why?
This is an app-sre requirement.

## How?
Added the `readiness` probe config in the deploy.yml

## Testing
N/A

## Anything Else?
Any other notes about the PR that would be useful for the reviewer. 

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by CodyWMitchell — CHANGES_REQUESTED** [review]
I believe the health endpoint is on `/health`, not `/v1/health` (double check me on that)

Also, does it make sense to have a separate endpoint from the liveness check?

Otherwise, LGTM

**Comment by tahmidefaz** [comment]
> I believe the health endpoint is on `/health`, not `/v1/health` (double check me on that)
> 
> Also, does it make sense to have a separate endpoint from the liveness check?
> 
> Otherwise, LGTM

Hey @CodyWMitchell , good question! I was actually following the `livenessProbe` config in that same file. The `readinessProbe` section is that I am adding here is identical with the `livenessProbe` section in the same file.  Also, it looks like there is already a `livenessProbe` and `readinessProbe` section in the `clowdapp.yml` that is using just the `/heath` endpoint, not sure what's going on there tbh :thinking:

**Review by aleccohan — CHANGES_REQUESTED** [review]
@tahmidefaz Based on the deploy.yml in app-interface for payload-tracker-go it looks like the clowder config file being used for deployment is `/deployments/clowdapp.yml` rather than `/deployments/deploy.yml` so these changes should be made there instead.

**Comment by tahmidefaz** [comment]
> @tahmidefaz Based on the deploy.yml in app-interface for payload-tracker-go it looks like the clowder config file being used for deployment is `/deployments/clowdapp.yml` rather than `/deployments/deploy.yml` so these changes should be made there instead.

Got it! Looks like there is already a readiness probe for the api in `clowdapp.yml`. Closing this PR and marking the ticket as done. Thank you!

**Pull request closed without merging**
