### PR TITLE
Refactoring some DB methods and making them more testable

### PR DESCRIPTION
**Pull request by tahmidefaz**
## What?
Merged the db_methods package with queries package. Now, we will have only one package for all db interactions.
Made the queries_api DB methods more testable.

[RHCLOUD-19058](https://issues.redhat.com/browse/RHCLOUD-19058)

## Why?
We can write more testable code for the API. I am planning to work on it next.

## How?
* discontinued the `db_methods` package and moved its contents to `queries`.
* `queries_api` methods now expects a `*gorm.DB` object. This will allow us to test the code in the future.

## Testing
Did you add any tests for the change?

## Anything Else?
Any other notes about the PR that would be useful for the reviewer. 

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
8c5b8072-b827-4323-bafa-e8aba96872af
bbce36fc-c87f-4fe3-a4cd-7110526620ac

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
3afff7f2-7afb-46a2-ba3c-0c4db4ed0c8c
523d3c3d-2022-41fd-8000-2fbb01e7a701

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
59a16521-c7c1-414e-8e49-71a3bab1fe1d
6fddb9ca-0887-49bc-a9e0-57d3ae04b0f0

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
3b22e8c7-926c-418a-ab47-dca39159eeab
9904cead-c8f2-4ab0-9a6b-80e1c3a25ec1

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
b26ea02a-d5ac-4638-a7e6-42c734f40253
cc204060-5980-4f79-8a5d-d7c8124231b5

**Review by SteveHNH — APPROVED** [review]
LGTM

**Pull request merged**
