### PR TITLE
Adding DB seeder script

### PR DESCRIPTION
**Pull request by tahmidefaz**

### CODE REVIEW

**Review by aleccohan — APPROVED** [review]
Tested and Validated the script!  This is awesome Tahmid TY

One minor thing though (Let me know what you think!) How do you feel about storing this in the "DB" folder in internal?  It makes sense to me to only keep running services in cmd and have the db stuff in other places.  Again though just a suggestion!  Let me know what you think!

**Comment by tahmidefaz** [comment]
> Tested and Validated the script! This is awesome Tahmid TY
> 
> One minor thing though (Let me know what you think!) How do you feel about storing this in the "DB" folder in internal? It makes sense to me to only keep running services in cmd and have the db stuff in other places. Again though just a suggestion! Let me know what you think!

@aleccohan Yeah, I actually didn't know where to put it tbh! Also, reading up on the `golang-standards/project-layout` a bit, it looks like the new [tools](https://github.com/golang-standards/project-layout/tree/master/tools) directory would be the perfect place for this. I will move it there, if that's alright with you? :thinking:

**Comment by aleccohan** [comment]
@tahmidefaz That sounds great to me!!  Yeah that feels like a perfect place to put this!

**Comment by tahmidefaz** [comment]
> @tahmidefaz That sounds great to me!! Yeah that feels like a perfect place to put this!

Done! :100:

**Pull request merged**
